### ISSUE TITLE
Copyright holder defaults to MaxMind, Inc.

### ISSUE THREAD

**Issue by PatrickCronin** [maxmind/Dist-Zilla-PluginBundle-MAXMIND#7]
I ran `dzil build` on the [Perl minFraud API client](https://github.com/maxmind/minfraud-api-perl) and found that my name was listed in the copyright. Then I added `copyright_holder = MaxMind, Inc.` to dist.ini and the copyright was returned to MaxMind, Inc.

**Comment by oschwald** [comment]
I am not sure anyone else has experienced this issue. Given that we are no longer releasing many Perl modules, I am going to close this.
