### ISSUE TITLE
WL: Add a plugin to generate a code of conduct

### ISSUE THREAD

**Issue by autarch** [maxmind/Dist-Zilla-PluginBundle-MAXMIND#8]
You can see how I did this in my bundle at https://github.com/autarch/Dist-Zilla-PluginBundle-DROLSKY/commit/2ff54ca29a10c331a8a5dd5fab8519e5f6a66d2f

**Comment by oschwald** [comment]
I am closing this as I don't think we are likely to do it. At this point, we are only releasing bug fixes for our Perl modules.
