### ISSUE TITLE
Dist::Zilla::Plugin::MAXMIND::TidyAll not properly indexed

### ISSUE THREAD

**Issue by eserte** [maxmind/Dist-Zilla-PluginBundle-MAXMIND#9]
There seems to be an indexing problem with Dist::Zilla::Plugin::MAXMIND::TidyAll --- it is indexed for an much older version of the PluginBundle:
```
cpan[2]> m Dist::Zilla::Plugin::MAXMIND::TidyAll                                
Module id = Dist::Zilla::Plugin::MAXMIND::TidyAll
    CPAN_USERID  MAXMIND (MaxMind, Inc. <support@maxmind.com>)
    CPAN_VERSION 0.13
    CPAN_FILE    M/MA/MAXMIND/Dist-Zilla-PluginBundle-MAXMIND-0.13.tar.gz
    UPLOAD_DATE  2016-06-17
    INST_FILE    (not installed)
```

**Comment by oschwald** [comment]
Thanks. I forced a reindexing.

**Comment by oschwald** [comment]
That didn't help. After looking a bit closer, it appears we specifically ask for those modules not be indexed: https://github.com/maxmind/Dist-Zilla-PluginBundle-MAXMIND/blob/4b6a20010a4206428e5bc3c084c70750b6990518/dist.ini#L22

I am not sure of the specific reason. It looks like that came from @autarch's bundle. Maybe he doesn't want others depending on his plugins.

**Comment by autarch** [comment]
Yeah, in my case I didn't think it was a good idea to expose those plugins for others to use, since I want to be free to remove or change them.

**Comment by eserte** [comment]
So @oalders should change the dependency here https://metacpan.org/source/OALDERS/Dist-Zilla-PluginBundle-Author-OALDERS-0.000024/dist.ini#L44 ?

**Comment by autarch** [comment]
> So @oalders should change the dependency here [metacpan.org/source/OALDERS/Dist-Zilla-PluginBundle-Author-OALDERS-0.000024/dist.ini#L44](https://metacpan.org/source/OALDERS/Dist-Zilla-PluginBundle-Author-OALDERS-0.000024/dist.ini#L44) ?

Well, that's up the maintainers of the MAXMIND bundle, but I would strongly suggest he _copy_ the tidyall plugin or work on creating one that is general enough to be shared as its own CPAN dependency.

**Comment by oschwald** [comment]
@oalders, any objections to just copying the plugin into your bundle? I don't have a strong feeling about this. I do agree that this is probably not the sort of thing that we would want third parties depending on generally.

**Comment by oalders** [comment]
Sure, I just copied it over to my bundle.  That should take care of it.
